### PR TITLE
Update to Actions CI + remove CircuitPython

### PR DESCRIPTION
**Pull request by brentru**
This Pull Request:
- Moving this repository from TravisCI to Actions. 
  - @ladyada  We can turn off Travis for this repository after this is merged :)
- Removed extra, outdated, CircuitPython code from this repository. This repository is **arduino only** (MetroX CircuitPython code is stored in https://github.com/adafruit/METROX-CircuitPython already)

Addresses issues: https://github.com/adafruit/METROX-Examples-and-Project-Sketches/issues/10, https://github.com/adafruit/METROX-Examples-and-Project-Sketches/issues/9

### CODE REVIEW

**Comment by ladyada** [comment]
hmm maybe better to just update the CI script? we have a special exception for learning repo already

**Comment by brentru** [comment]
@ladyada I'll take a look at the CI script.

**Comment by brentru** [comment]
@ladyada CI script has been updated and the original `arduino/` directory has been restored so we dont need to update guide URLs. **OK to merge?** 

Passing on https://github.com/brentru/METROX-Examples-and-Project-Sketches-1/actions/runs/416213086

**Comment by ladyada** [comment]
yep!

**Pull request merged**
